openapi: 3.0.3
info:
  title: Financial report API
  version: 1.0.0
paths:
  /report/getCurrentReport:
    get:
      summary: get current report
      operationId: getCurrentReport
      tags:
        - Report
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialReport'
        '404':
          description: report not found
  /report/moveTransaction:
    post:
      summary: move transaction within a report
      operationId: moveTransaction
      tags:
        - Report
      requestBody:
        $ref: '#/components/requestBodies/moveTransactionBody'
      responses:
        '204':
          description: successful operation
        '400':
          description: bad request

components:
  schemas:
    FinancialReport:
      type: object
      required:
        - categories
        - sections
        - columns
      properties:
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        sections:
          type: array
          items:
            $ref: '#/components/schemas/ReportSection'
        columns:
          type: array
          items:
            $ref: '#/components/schemas/Column'
    Category:
      type: object
      required:
        - id
        - name
        - position
        - sign
        - type
      properties:
        id:
          type: string
        name:
          type: string
        position:
          type: number
        sign:
          type: number
          enum:
            - -1
            - 1
        type:
          $ref: '#/components/schemas/CategoryType'
    CategoryType:
      type: string
      enum:
        - data
        - profit
        - netincome
    Column:
      type: object
      required:
        - id
        - title
        - date
      properties:
        id:
          type: string
        title:
          type: string
        date:
          type: string
          format: date-time
    ReportSection:
      type: object
      required:
        - id
        - name
        - category
        - data
      properties:
        id:
          type: string
        name:
          type: string
        category:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/CellData'
    CellData:
      type: object
      required:
        - value
        - transactions
      properties:
        value:
          $ref: '#/components/schemas/CellValue'
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    CellValue:
      type: number
      nullable: true
    Transaction:
      type: object
      required:
        - id
        - date
        - name
        - value
      properties:
        id:
          type: string
        date:
          type: string
        name:
          type: string
        value:
          type: number
  requestBodies:
    moveTransactionBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - transactionId
              - fromSection
              - toSection
            properties:
              transactionId:
                type: string
              fromSection:
                type: string
              toSection:
                type: string
